server:
    port: 8109

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/spring-config/

    profiles:
        active: native
