spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:4200" # Array format required
            allowed-methods: 
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true # Must be lowercase
            exposed-headers: 
              - Set-Cookie # Required for cookies
              - Authorization