server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: authentication-service
  
  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: email

# Swagger configuration
springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    path: /auth/swagger-ui.html

# Include shared configurations
include:
  - shared/datasource-config.yml
  - shared/kafka-config.yml
  - shared/security-config.yml
  - shared/logging-config.yml
  - shared/eureka-client.yml