server:
  port: ${EUREKA_SERVER_PORT}

spring:
  application:
    name: discovery-service
  
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0

# Include shared logging configuration
include:
  - shared/logging-config.yml