spring:
  profiles: dev
  
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

include:
  - shared/security-config.yml
  - shared/logging-config.yml
  - shared/eureka-client.yml
