
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allow-credentials: true
                        allowed-headers: '*'
                        allowed-methods:
                        - GET
                        - POST
                        - PUT
                        - DELETE
                        - OPTIONS
                        allowed-origins:
                        - http://localhost:4200
                        exposed-headers:
                        - Set-Cookie
                        - Authorization
# Discovery service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"




server:
    port: 8080
springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Dashboard Service
        url: /dashboard/v3/api-docs
      - name: History Service
        url: /history/v3/api-docs
      - name: Notification Service
        url: /notification/v3/api-docs
      - name: Transaction Service
        url: /transaction/v3/api-docs
      - name: User Management Service
        url: /user/v3/api-docs
      - name: Wallet Service
        url: /wallet/v3/api-docs