server:
    port: 8080
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allow-credentials: true
                        allowed-headers: '*'
                        allowed-methods:
                        - GET
                        - POST
                        - PUT
                        - DELETE
                        - OPTIONS
                        allowed-origins:
                        - http://localhost:4200
                        exposed-headers:
                        - Set-Cookie
                        - Authorization
# Discovery service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
      
