spring:
  profiles: prod
  
logging:
  level:
    root: WARN
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO

# Include shared configurations
include:
  - shared/security-config.yml
  - shared/logging-config.yml
  - shared/eureka-client.yml
