server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-headers: ${CORS_ALLOWED_HEADERS}
            allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowed-origins: ${CORS_ALLOWED_ORIGINS}
            exposed-headers:
            - Set-Cookie
            - Authorization

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Dashboard Service
        url: /dashboard/v3/api-docs
      - name: History Service
        url: /history/v3/api-docs
      - name: Notification Service
        url: /notification/v3/api-docs
      - name: Transaction Service
        url: /transaction/v3/api-docs
      - name: User Management Service
        url: /user/v3/api-docs
      - name: Wallet Service
        url: /wallet/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

include:
  - shared/security-config.yml
  - shared/logging-config.yml
  - shared/eureka-client.yml