server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-headers: ${CORS_ALLOWED_HEADERS}
            allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowed-origins: ${CORS_ALLOWED_ORIGINS}
            exposed-headers:
            - Set-Cookie
            - Authorization
      routes:
        - id: auth-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: dashboard-service
          uri: lb://dashboard-service
          predicates:
            - Path=/dashboard/**
          filters:
            - StripPrefix=1
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/wallet/**
          filters:
            - StripPrefix=1
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-management-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/history/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1

# Swagger configuration for API gateway
springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Dashboard Service
        url: /dashboard/v3/api-docs
      - name: History Service
        url: /history/v3/api-docs
      - name: Notification Service
        url: /notification/v3/api-docs
      - name: Transaction Service
        url: /transaction/v3/api-docs
      - name: User Management Service
        url: /user/v3/api-docs
      - name: Wallet Service
        url: /wallet/v3/api-docs

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Include shared configurations
include:
  - shared/security-config.yml
  - shared/logging-config.yml
  - shared/eureka-client.yml