server:
    port: 8089
spring:
    application:
        name: user-managment-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456789
        url: jdbc:mysql://localhost:3306/user_management_service
        username: root
    jackson:
        serialization:
            write-dates-as-timestamps: false
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: earliest
            group-id: user-management-service
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                spring:
                    json:
                        trusted:
                            packages: "*"
                        value:
                            default:
                                type: com.themoneywallet.usermanagmentservice.event.Event
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                spring:
                    json:
                        add:
                            type:
                                headers: false
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    web:
        resources:
            add-mappings: false

# Discovery service
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8888/eureka
springdoc:
  api-docs:
    path: /user/v3/api-docs
  swagger-ui:
    path: /user/swagger-ui.html
