eureka:
    client:
        service-url:
            defaultZone: http://localhost:8888/eureka

server:
    port: 8109

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/spring-config/

    profiles:
        active: native
