


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8888/eureka


server:
  port: 8098

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///opt/spring-config/
  profiles:
    active: native