server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: config-server
  profiles:
    active: native
  
 
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO