erDiagram
    USER_CREDENTIAL {
        string id PK
        string email
        string userName
        string password
        string userRole
        timestamp validUntil
        boolean locked
        boolean enabled
        string emailVerificationToken
        timestamp emailVerificationTokenExpiry
        string passwordResetToken
        timestamp passwordResetTokenExpiry
        string token
        timestamp expiryDateOfTokenInstant
        string ipAddress
        boolean revoked
    }
    


   