package com.themoneywallet.historyservice.event;

public enum EventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    TOKEN_EXPIRED,
    SIGN_UP,
    EMAIL_VERIFIY,
    EMAIL_NOTIFCATION,
    FORGET_PASSWORD,
    CREATE_PROFILE,
    USER_PROFILE_CREATED,
    CREATED_WALLET,
    WALLET_STATUS_CHANGED,
    WALLET_LIMIT_UPDATED,
    WALLET_ADD_FUND,
    WALLET_REMOVE_FUND,
    WALLET_DELETED,
     TRANSFER_TRANSACTION_START,
}
