logging:
  level:
    root: ${LOG_LEVEL_ROOT}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY}
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY}
    org.springframework.transaction: ${LOG_LEVEL_TRANSACTION}
    org.springframework.orm.jpa: ${LOG_LEVEL_JPA}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BINDER}
    
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  file:
    name: ${LOG_FILE_PATH}/${spring.application.name}.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 100MB
    
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE_PATH}/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      total-size-cap: 100MB
      max-history: 7