app:
  security:
    jwt:
      expiration: ${JWT_EXPIRATION}
      secret-key: ${JWT_SECRET_KEY}
      token-prefix: "Bearer "
      header-name: "Authorization"
      authorities-key: "authorities"
      refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: ${CORS_ALLOWED_HEADERS}
    exposed-headers: ${CORS_EXPOSED_HEADERS}
    allow-credentials: true
    max-age: 3600
  
spring:
  security:
    filter:
      order: 10
    require-ssl: false