package com.themoneywallet.sharedUtilities.enums;

public enum EventType {
    AUTH_USER_LOGIN_SUCCESSED,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    TOKEN_EXPIRED,
    AUTH_USER_SIGN_UP,
    EMAIL_VERIFIY,
    EMAIL_NOTIFCATION,
    FORGET_PASSWORD,
    CREATE_PROFILE,
    USER_PROFILE_CREATED,
    USER_PROFILE_DELETED,
    USER_PROFILE_UPDATED
    ,
    CREATED_WALLET,
    WALLET_STATUS_CHANGED,
    WALLET_LIMIT_UPDATED,
    WALLET_ADD_FUND,
    WALLET_REMOVE_FUND,
    WALLET_DELETED,
    TRANSFER_TRANSACTION_START,
}
