package com.themoneywallet.sharedUtilities.enums;

public enum EventType {
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILURE,
    USER_LOGOUT,
    USER_PASSWORD_CHANGE,
    USER_ACCOUNT_LOCK,
    USER_ACCOUNT_UNLOCK,
    USER_TOKEN_EXPIRATION,
    USER_REGISTRATION,
    USER_EMAIL_VERIFICATION,
    USER_EMAIL_NOTIFICATION,
    USER_FORGOT_PASSWORD,
    USER_PROFILE_CREATION,
    USER_PROFILE_DELETION,
    USER_PROFILE_UPDATE,
    WALLET_CREATION,
    WALLET_BALANCE_CHANGE,
    WALLET_STATUS_CHANGE,
    WALLET_LIMIT_UPDATE,
    WALLET_FUND_ADDITION,
    WALLET_FUND_REMOVAL,
    WALLET_DELETION,
    TRANSACTION_TRANSFER_START
}
