apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: themoneywallet/transaction-service:1.0.0 # Replace with your actual image name and tag
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod # Use 'prod' profile for Kubernetes deployment
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8109 # Assuming config-service is accessible via this hostname
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/ # Assuming eureka-service is accessible
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/themoneywallet_transactions?useSSL=false&serverTimezone=UTC # Assuming mysql-service
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password # Consider using Kubernetes Secrets for production
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092 # Assuming kafka-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 5
