apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP # Use ClusterIP for internal service, NodePort or LoadBalancer for external access
