package com.walletservice.event;


 public enum EventType {
        LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT, PASSWORD_CHANGED, 
        ACCOUNT_LOCKED, ACCOUNT_UNLOCKED, TOKEN_EXPIRED ,SIGN_UP,
        EMAIL_VERIFIY , EMAIL_NOTIFCATION , FORGET_PASSWORD,
        CREATE_PROFILE, USER_PROFILE_CREATED , CREATED_DEFAULT_WALLET

    }
    

   