version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: ${ELASTIC_CONTAINER_NAME}
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ELASTIC_JAVA_OPTS}
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    networks:
      - ${NETWORK_NAME}

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: ${KIBANA_CONTAINER_NAME}
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_ES_HOST}
    depends_on:
      - elasticsearch
    networks:
      - ${NETWORK_NAME}

  logstash:
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION}
    container_name: ${LOGSTASH_CONTAINER_NAME}
    ports:
      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    environment:
      - xpack.monitoring.enabled=${LOGSTASH_MONITORING_ENABLED}
    networks:
      - ${NETWORK_NAME}

networks:
  ${NETWORK_NAME}:
    driver: bridge

