version: '3.9'

services:
  JENKINS:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "${JENKINS_PORT_OUTSIDE}:${JENKINS_PORT_INSIDE}"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/mohamed/Desktop/TheMoneyWallet-TheMMPay:/projects/TheMoneyWallet-TheMMPay
    networks:
      - shared-net

volumes:
  jenkins_home:

networks:
  shared-net:
    driver: bridge

