server:
    port: 8090
spring:
    application:
        name: wallet-service
    data:
        redis:
            host: localhost
            port: 6379
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456789
        url: jdbc:mysql://localhost:3306/wallet_service
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: earliest
            group-id: wallet-service
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                spring:
                    json:
                        trusted:
                            packages: '*'
                        value:
                            default:
                                type: com.walletservice.event.Event
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                spring:
                    json:
                        add:
                            type:
                                headers: false
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    redis:
        host: localhost
        port: 6379
        timeout: 60000


# Discovery service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
      

otel:
  traces:
    exporter:
      otlp:
        endpoint: http://localhost:4317
  metrics:
    exporter:
      otlp:
        endpoint: http://localhost:4317
  resource:
    attributes: service.name=my-spring-boot-app
  sampler:
    probability: 1.0


app:
  jwt:
    expiration: 86400
    secret-access: "b2phbHpsdU54Z3htb2NSanBCK3ErWkxOeFNmeTdiZk9XNkR2NEt0Mkhraz0=" 
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"